# ------------------------------------------------------------- Project CI --- #

stages:
    - build
    - deploy
default:
  image: ubuntu:22.04

build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/backend:latest"

build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/frontend:latest"

deploy:
  stage: deploy
  image: docker:latest
  script:
    - echo "${{ secrets.EC2_SSH_KEY }}" > private_key
    - ssh -o StrictHostKeyChecking=no -i private_key ${EC2_URI} &&
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker pull ${CI_REGISTRY_IMAGE}/frontend:latest &&
      docker pull ${CI_REGISTRY_IMAGE}/backend:latest &&
      cd nlpf &&
      git pull "${{ secrets.GITLAB_CLONE }}" &&
      docker-compose up -d
